backend:
  name: git-gateway
  branch: master
media_folder: content/img
public_folder: img
collections:
  - label: "Educators"
    name: "educators/educators"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Color",name: color,widget: "select",default: "primary" , options:  [{ label: "Blue", value: "primary" }, { label: "Pink", value: "secondary" }, { label: "Yellow", value: "accent" }]}
      - {label: "Description", name: "text", widget: "markdown"}
      - {label: Contact, name: contact, widget: object, fields: [{label: Email, name: email, widget: string}, {label: Phone, name: phone, widget: string}]}
  - label: "Services"
    name: "blog"
    folder: "content/services"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Color",name: color,widget: "select",default: "primary" , options:  [{ label: "Blue", value: "primary" }, { label: "Pink", value: "secondary" }, { label: "Yellow", value: "accent" }]}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Hero, name: hero, widget: object,
             fields: [{
                        label: Heading,name: heading,widget: list,
                        fields: [
                        {label: Text,name: text,widget: text},
                        {label: "Color",name: underlineColor,widget: "select",default: "primary" , options:  [{ label: "Blue", value: "primary" }, { label: "Pink", value: "secondary" }, { label: "Yellow", value: "accent" }]},
                        {label: "New Line After this Text", name: lineBreak, widget: boolean, default: true}]
                      },
                      {label: Button, name: buttonText, widget: text}]
          }
          - {label: "Mission & Values", name: mission, widget: object,
             fields: [{
                        label: Heading,name: heading,widget: list,
                        fields: [
                        {label: Text,name: text,widget: text},
                        {label: "Color",name: underlineColor,widget: "select",default: "primary" , options:  [{ label: "Blue", value: "primary" }, { label: "Pink", value: "secondary" }, { label: "Yellow", value: "accent" }]},
                        {label: "New Line After this Text", name: lineBreak, widget: boolean, default: true}]
                      },
                      {label: Text, name: text, widget: text},
                      {label: Values,name: values,widget: list}
             ]
          }
          - {label: "Our Services", name: services, widget: object,
             fields: [{
                        label: Heading,name: heading,widget: list,
                        fields: [
                        {label: Text,name: text,widget: text},
                        {label: "Color",name: underlineColor,widget: "select",default: "primary" , options:  [{ label: "Blue", value: "primary" }, { label: "Pink", value: "secondary" }, { label: "Yellow", value: "accent" }]},
                        {label: "New Line After this Text", name: lineBreak, widget: boolean, default: true}]
                      },
                      {label: Text, name: text, widget: text},
             ]
          }
